-- vim.cmd "packadd packer.nvim"
-- 
-- local packer = require('packer')
-- 
-- packer.startup(function(use)
--   -- Package manager
--   use({ 'wbthomason/packer.nvim' })
-- 
--   -- MoonScript support
--   use({ 'leafo/moonscript-vim' })
--   use({ 'svermeulen/nvim-moonmaker' })
-- 
--   -- WhichKey is used by many parts of the config, so load it first.
--   use({
--     'folke/which-key.nvim',
--     config = function()
--       local whichkey = require('which-key')
-- 
--       whichkey.setup({
--         -- plugins = {
--         --   marks = false,
--         --   registers = false,
--         --   spelling = { enabled = false, suggestions = 20 },
--         --   presets = {
--         --     operators = false,
--         --     motions = false,
--         --     text_objects = false,
--         --     windows = false,
--         --     nav = false,
--         --     z = false,
--         --     g = false,
--         --   },
--         --   window = { border = 'single', position = 'top', margin = { 1, 0, 1, 0 }, padding = { 2, 2, 2, 2 } },
--         --   layout = { height = { min = 4, max = 25 }, width = { min = 20, max = 50 }, spacing = 3, align = 'center' },
--         -- },
--       })
--     end,
--   })
-- 
--   require('backups')(use)
--   require('buffers')(use)
--   require('close-file')(use)
--   require('colorschemes')(use)
--   require('completion')(use)
--   require('copy-paste')(use)
--   require('debugger')(use)
--   require('file-tabs')(use)
--   require('file-tree-sidebar')(use)
--   require('folds')(use)
--   require('indentation')(use)
--   require('line-numbers')(use)
--   require('movement')(use)
--   require('quickfix')(use)
--   require('save-file')(use)
--   require('search')(use)
--   require('splits')(use)
--   require('status-line')(use)
--   require('visual-information')(use)
-- 
-- end)
-- 
-- -- Disable NetRW
-- vim.g.loaded_netrw = 1
-- vim.g.loaded_netrwPlugin = 1
-- 
-- -- Set the map leader to space
-- vim.g.mapleader = ' '
